apiVersion: v2
name: llmkube
description: >-
  A Helm chart for LLMKube - Kubernetes operator for GPU-accelerated LLM
  inference
type: application
version: 0.8.28
appVersion: 0.8.28
keywords:
  - llm
  - kubernetes
  - operator
  - gpu
  - inference
  - ai
  - machine-learning
home: https://github.com/defilantech/LLMKube
sources:
  - https://github.com/defilantech/LLMKube
maintainers:
  - name: Chris Maher
    email: contact@defilan.com
annotations:
  helm.sh/resource-policy: keep
